[settings]
idiomatic_version_file_enable_tools = []

[settings.node]
gpg_verify = false

[tools]
gemini-cli = "latest"
node = "latest"
"npm:yarn" = "latest"
"npm:@openai/codex" = "latest"
python = "latest"
uv = "latest"

